// <auto-generated />
namespace WebDACS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AllTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202305261515171_AllTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
